#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
new_string="root /var/www/example.com;\n\tindex index.html;\n\tlocation /redirect_me {\n\t\treturn 301 https://bolexzy.hashnode.dev/;\n\t}\n"

sudo sed -i "s|root /var/www/html;|${new_string}|" /etc/nginx/sites-available/default
sudo service nginx reload
